# Execution configuration
experiment_name: baseline  # Name for this ablation experiment

output:
  folder: ./output

experiments:
  run_id: 0

dataset:
  name: medqa
  dir: ./data
  split: test_hard

model:
  name: gpt-4o-mini
  temperature: 0.0
